@extends('enablers.app.layouts.app')

@section('page-title'," | Terms & Conditions")

@section('styles')
@endsection

@section('content')
    <section id="p-inner" class="e-banner-wrapper pr-4 pr-lg-5">
        <div id="inner-content" class="content">
            <div class="container-fuild">
                <div class="row no-gutters align-items-center">
                    <div class="col-lg-6 animate__animated animate__animated animate__fadeInLeft">
                        <div class="support-left-content main-headings">
                            <h1 class="text-white h-primary text-uppercase">Terms & Conditions</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-bar"></div>
    </section>

    <!--  Start Banner Wrapper -->
    <section class="e-bluid-wrapper padd">
        <div class="content">
            <div class="container">
                <div class="row align-items-center">
                    <div class="mt-5">
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Agreement between user and enablers.org.</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">The https://www.enablers.org website (the “Site”) is comprised of various web pages operated by enablers.org, it is offered to you conditioned on your acceptance without modification of the terms, conditions, and notices contained herein (the “Terms”). Your use of https://www.enablers.org constitutes your agreement to all such Terms. Please read these terms carefully, and keep a copy of them for your reference.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">enablers.org provides online and offline training that offers online entrepreneurship education courses</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Electronic Communications</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">Visiting https://www.enablers.org or sending emails to enablers.org constitutes electronic communications. You consent to receive electronic communications and you agree that all agreements, notices, disclosures and other communications that we provide to you electronically, via email and on the Site, satisfy any legal requirement that such communications be in writing.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Your Account</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. You may not assign or otherwise transfer your account to any other person or entity. You acknowledge that enablers.org is not responsible for third party access to your account that results from theft or misappropriation of your account. enablers.org and its associates reserve the right to refuse or cancel service, terminate accounts, or remove or edit content in our sole discretion.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">enablers.org does not knowingly collect, either online or offline, personal information from persons under the age of thirteen. If you are under 18, you may use https://www.enablers.org only with permission of a parent or guardian.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Refund/Cancellation Policy</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">enablers.org do not offer any refund policy.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Links to Third Party Sites/Third Party Services</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">https://www.enablers.org may contain links to other websites (“Linked Sites”). The Linked Sites are not under the control of enablers.org and is not responsible for the contents of any Linked Site, including without limitation any link contained in a Linked Site, or any changes or updates to a Linked Site enablers.org is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by enablers.org of the site or any association with its operators.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">Certain services made available via https://www.enablers.org are delivered by third party sites and organizations. By using any product, service or functionality originating from the https://www.enablers.org domain, you hereby acknowledge and consent that enablers.org may share such information and data with any third party with whom&nbsp;enablers.org has a contractual relationship to provide the requested product, service or functionality on behalf of https://www.enablers.org users and customers.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">All content included as part of the Service, such as text, graphics, logos, images, as well as the compilation thereof, and any software used on the Site, is the property of enablers.org or its suppliers and protected by copyright and other laws that protect intellectual property and proprietary rights. You agree to observe and abide by all copyright and other proprietary notices, legends or other restrictions contained in any such content and will not make any changes thereto.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">You will not modify, publish, transmit, reverse engineer, participate in the transfer or sale, create derivative works, or in any way exploit any of the content, in whole or in part, found on the Site. enablers.org content is not for sale or resale. You are purchasing licensing access to use the site to access the content ONLY, you are not purchasing any ownership to the content itself, and therefore have no rights to the content. Your use of the Site does not entitle you to make any unauthorized use of any protected content, and in particular you will not delete or alter any proprietary rights or attribution notices in any content. You will use protected content solely for your personal use, and will make no other use of the content without the express written permission of enablers.org and the copyright owner. You agree that you do not acquire any ownership rights in any protected content. We do not grant you any licenses, express or implied, to the intellectual property of enablers.org or our licensors except as expressly authorized by these Terms.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Use of Communication Services</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">The Site may contain bulletin board services, chat areas, news groups, forums, communities, personal web pages, calendars, and/or other message or communication facilities designed to enable you to communicate with the public at large or with a group (collectively, “Communication Services”), you agree to use the Communication Services only to post, send and receive messages and material that are proper and related to the particular Communication Service.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">By way of example, and not as a limitation, you agree that when using a Communication Service, you will not: defame, abuse, harass, stalk, threaten or otherwise violate the legal rights (such as rights of privacy and publicity) of others; publish, post, upload, distribute or disseminate any inappropriate, profane, defamatory, infringing, obscene, indecent or unlawful topic, name, material or information; upload files that contain software or other material protected by intellectual property laws (or by rights of privacy of publicity) unless you own or control the rights thereto or have received all necessary consents; upload files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of another’s computer; advertise or offer to sell or buy any goods or services for any business purpose, unless such Communication Service specifically allows such messages; conduct or forward surveys, contests, pyramid schemes or chain letters; download any file posted by another user of a Communication Service that you know, or reasonably should know, cannot be legally distributed in such manner; falsify or delete any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded, restrict or inhibit any other user from using and enjoying the Communication Services; violate any code of conduct or other guidelines which may be applicable for any particular Communication Service; harvest or otherwise collect information about others, including e-mail addresses, without their consent; violate any applicable laws or regulations.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">enablers.org has no obligation to monitor the Communication Services. However, enablers.org reserves the right to review materials posted to a Communication Service and to remove any materials in its sole discretion. enablers.org reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever.</span></p><p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">enablers.org reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in enablers.org sole discretion.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">Always use caution when giving out any personally identifying information about yourself or your children in any Communication Service. enablers.org does not control or endorse the content, messages or information found in any Communication Service and, therefore, enablers.org specifically disclaims any liability with regard to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized enablers.org&nbsp; spokespersons, and their views do not necessarily reflect those of enablers.org</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">Materials uploaded to a Communication Service may be subject to posted limitations on usage, reproduction and/or dissemination. You are responsible for adhering to such limitations if you upload the materials.</span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;"><strong>Modifications</strong></span></p>
                        <p><span style="color: #000000; font-size: 22px; text-align: justify; line-height: 31px;">enablers.org may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</span></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--  End Banner Wrapper -->
@endsection

@section('scripts')
@endsection
